options:
  dns-backend:
    default:
    type: string
    description: IP Address of dns backend
  nova-domain:
    default: 'www.example.com.'
    type: string
    description: Domain to add records for new instances to
  nova-domain-email:
    default: 'email@example.com'
    type: string
    description: Email address of the person responsible for the domain.
  dns-server-record:
    default: 'ns1.www.example.com.'
    type: string
    description: DNS server record
  neutron-domain:
    default: 'www.bob.com.'
    type: string
    description: Domain to add  floating ip recirds to
  neutron-domain-email:
    default: 'email@example.com'
    type: string
    description: Email address of the person responsible for the domain.
  vip:
    type: string
    default:
    description: |
      Virtual IP(s) to use to front API services in HA configuration.

      If multiple networks are being used, a VIP should be provided for each
      network, separated by spaces.
  vip_iface:
    type: string
    default: eth0
    description: |
      Default network interface to use for HA vip when it cannot be
      automatically determined.
  vip_cidr:
    type: int
    default: 24
    description: |
      Default CIDR netmask to use for HA vip when it cannot be automatically
      determined.
